name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 */6 * * *'   # كل 6 ساعات
  workflow_dispatch:         # زرار Run manually بعد ما تخلص أي room

jobs:
  tryhackme-badge-update:
    name: Update THM badge image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "Hackth3Path"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
